# Generated by Django 3.2 on 2026-02-26 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('movies_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='评分')),
                ('timestamp', models.BigIntegerField(verbose_name='时间戳')),
                ('datetime', models.DateTimeField(verbose_name='评分时间')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='原始行号')),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='movies.movie', verbose_name='电影')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='movies_users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
                'db_table': 'ratings',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'rating'], name='ratings_user_id_b7af4c_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie', 'rating'], name='ratings_movie_i_e0416e_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['datetime'], name='ratings_datetim_6fe394_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
    ]
