# Generated by Django 3.2 on 2026-02-26 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], help_text='F=女性，M=男性', max_length=1, verbose_name='性别')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='年龄')),
                ('age_group', models.CharField(choices=[('Under 18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-49', '45-49'), ('50-55', '50-55'), ('56+', '56+')], max_length=10, verbose_name='年龄组')),
                ('occupation_code', models.CharField(max_length=5, verbose_name='职业编码')),
                ('occupation', models.CharField(max_length=50, verbose_name='职业名称')),
                ('zip_code', models.CharField(max_length=20, verbose_name='邮政编码')),
            ],
            options={
                'verbose_name': '电影用户信息',
                'verbose_name_plural': '电影用户信息',
                'db_table': 'movies_users',
                'ordering': ['user_id'],
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['gender'], name='movies_user_gender_e77ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['age_group'], name='movies_user_age_gro_5e799b_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['occupation'], name='movies_user_occupat_e4e1a5_idx'),
        ),
    ]
