# Generated by Django 3.2 on 2026-04-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clicked_movie_ids',
            field=models.JSONField(default=list, verbose_name='点击历史序列'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='collected_movie_ids',
            field=models.JSONField(default=list, verbose_name='收藏序列'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_user_embedding',
            field=models.BinaryField(blank=True, null=True, verbose_name='用户嵌入向量'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='point_count',
            field=models.IntegerField(default=0, verbose_name='点击次数'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_genres',
            field=models.JSONField(default=list, verbose_name='偏好类型'),
        ),
    ]
