# Generated by Django 3.2 on 2026-04-09 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20260401_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieWatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(verbose_name='电影ID')),
                ('watch_time', models.DateTimeField(auto_now=True, verbose_name='观看时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='观看用户')),
            ],
            options={
                'verbose_name': '电影观看记录',
                'verbose_name_plural': '电影观看记录',
                'ordering': ['-watch_time'],
                'unique_together': {('user', 'movie_id')},
            },
        ),
    ]
