# Generated by Django 3.2 on 2026-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_moviewatchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='是否发送邮件'),
        ),
    ]
