# Generated by Django 3.2 on 2026-04-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_explore',
            field=models.BooleanField(default=False, verbose_name='开启探索模式'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_monday_push',
            field=models.BooleanField(default=False, verbose_name='周一特刊推送'),
        ),
    ]
