# Generated by Django 3.2.25 on 2026-05-11 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_avg_rating'),
        ('user', '0008_movierating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rec_group',
            field=models.CharField(default='A', max_length=1, verbose_name='实验分组'),
        ),
        migrations.CreateModel(
            name='RecEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', '点击'), ('collect', '收藏'), ('rating', '评分'), ('impression', '展示')], max_length=10)),
                ('rec_group', models.CharField(max_length=1)),
                ('source', models.CharField(choices=[('homepage', '首页推荐'), ('rank', '排行榜'), ('detail_rec', '详情页推荐'), ('search', '搜索')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '实验事件记录',
                'verbose_name_plural': '实验事件记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recevent',
            index=models.Index(fields=['rec_group', 'event_type'], name='user_receve_rec_gro_85d565_idx'),
        ),
        migrations.AddIndex(
            model_name='recevent',
            index=models.Index(fields=['user', 'created_at'], name='user_receve_user_id_ff711e_idx'),
        ),
    ]
