# Generated by Django 3.2 on 2026-02-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='电影ID')),
                ('title', models.CharField(max_length=255, verbose_name='电影标题')),
                ('year', models.IntegerField(verbose_name='上映年份')),
                ('genres', models.CharField(max_length=255, verbose_name='电影类型')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'db_table': 'movies',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
