# Generated by Django 3.2 on 2026-03-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='平均评分'),
        ),
    ]
